server:
  port: 28080
  servlet:
    context-path: /tr-cloud-core-gen
spring:
  mvc:
    dispatch-options-request: true
    pathmatch:
      matching-strategy: ant-path-matcher
  dataSource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: ${db.username}
    password: ${db.password}
    url: jdbc:mysql://${db.ip}:${db.port}/${db.schema}?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&zeroDateTimeBehavior=CONVERT_TO_NULL&allowPublicKeyRetrieval=true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
db:
  ip: 169.254.99.183
  port: 3306
  schema: jygk_data
  username: root
  password: root
  type: MYSQL